language: node_js
node_js:
- '12'
branchs:
  only:
  - master
script: npm run build
before_install:
- openssl aes-256-cbc -K $encrypted_3d92ad42968a_key -iv $encrypted_3d92ad42968a_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
addons:
  ssh_known_hosts: 1.15.222.63
after_success:
  - scp -o stricthostkeychecking=no -r ./dist/* root@1.15.222.63:/root/notebook